### ISSUE TITLE
can't read netcdf v4

### ISSUE THREAD

**Issue by shinnobi** [cheminfo/netcdfjs#16]
thanks you for your project but i have a problem when read netcdf v4.

**Comment by maasencioh** [comment]
Hello, I'm sorry but currently we don't support v4 files 😞

**Comment by maasencioh** [comment]
This will be a major change on the implementation, for the recursive nature of the definition. If you have the time @polluxll @floriancochard for this implementation, this will be great and I'll try to guide you as much as I can.
