### ISSUE TITLE
Diffrence with H5 / HDF5 file format

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/netcdfjs#25]
More and more instrument produce HDF5 format and I wonder how similar it is from netcdf and if the right place for the parser is in this project.

https://docs.fileformat.com/misc/h5/#:~:text=H5%20File%20Viewer-,What%20is%20an%20H5%20file%3F,for%20quick%20retrieval%20and%20analysis.

**Comment by targos** [comment]
This is related to https://github.com/cheminfo/hdf5/issues/1
